#########################################################
#  	SCRIPT TO GENERATE COVERAGE GRAPHS AND TABLES.		#
#########################################################
# 1. Reads bedtools coverage file. 
# 2. Create new table grouped by genome, containing the % of bp at each depth (diffFracBelowThreshold), and the acummulated sum (1-cumsum(diffFracBelowThreshold).
# 3. Create new table grouped by genome, containing mean, median, min, max and sd.
# 4. New table grouped by genome and containing the % of coverage at 4 depth intervals and the total of the genome. 
# 5. Merge statistics and coverage tables.
# 6. Plot the data. 
# Note: This script is run after calculating the coverage with bedtools in the coverage.sh script.

# Arguments:
# $1 (sampleCoverageDir) = Directory with the sample coverage. (ANALYSIS/xx-organism/sampleName/coverage/)
# $2 (sampleName) = (sampleName)

# Input files: (In sampleCoverageDir)
# sampleName_genome_coverage.txt: file with the coverage data generated by bedtools.

# Output files: (In ANALYSIS/xx-organism/sampleName/blast/)
# sampleName_coverageTable.txt: File with statistic and coverage values.
# genomeId_coverage_graph.pdf: File with the coverage graph for each genome present in the sample

# Load libraries
library(ggplot2)
library(RColorBrewer)
library(plyr)

# get arguments
args = commandArgs(trailingOnly=TRUE)
sampleCoverageDir=args[1] # /workingDir/ANALYSIS/xx-organism/sampleName/coverage/
sampleName=args[2] # sampleName

result = tryCatch({
	# read bedtools file
	df=read.table(paste(sampleCoverageDir,sampleName,'_genome_coverage.txt',sep = ''), sep="\t")
	# Name each column
	colnames(df) <- c("gnm","covThreshold","fractionAtThisCoverage","genomeLength","diffFracBelowThreshold")
	# df: 
	# gnm			covThreshold	fractionAtThisCoverage	genomeLength	diffFracBelowThreshold
	# NC_006641.1	0				15865					15959			0.99411
	# NC_006641.1	1				94						15959			0.00589009
	# NC_003216.1	0				40515					40834			0.992188
	# ...

	# Create new table grouped by genome, containing the % of bp at each depth (diffFracBelowThreshold), and the acummulated sum (1-cumsum(diffFracBelowThreshold).
	cov <- ddply(df,.(gnm),summarize,covThreshold=covThreshold,diffFracBelowThreshold=diffFracBelowThreshold,fracAboveThreshold=1-cumsum(diffFracBelowThreshold))
	# cov:
	#         gnm covThreshold fracAboveThreshold
	# AC_000001.1            5               0.60  -> en el genoma AC_000001.1 hay un 60% de pb que están a una profundidad >= 5
	# AC_000001.1            7               0.33  -> en el genoma AC_000001.1 hay un 33% de pb que están a una profundidad >= 7
	# AC_000003.1            0               0
	# AC_000002.1            4               0.17  -> en el genoma AC_000002.1 hay un 17% de pb que están a una profundidad >= 4
	# ...

	# Create new table grouped by genome, containing mean, median, min, max and sd.
	new_cov <- ddply(cov,.(gnm),summarize,covMean=mean(covThreshold),covMin=min(covThreshold),covSD=sd(covThreshold),covMedian=median(covThreshold))

	# new_cov:
	# gnm 			covMean covMin    covMax covSD 		covMedian
	# AC_000001.1       250      0      500    217        123
	# AC_000002.1       100      0      200    78         98
	# AC_000003.1       0        0      0      NA         0
	# AC_000004.1       500      0      1000   98         843
	#write.table(new_cov, file=paste(sampleCoverageDir,sampleName,"_new_cov.txt", sep= ''),sep="\t", row.names=F)

	# New table grouped by genome and containing the % of coverage at 4 depth intervals and the total of the genome. 
	summary_cov <- by(cov, cov[,"gnm"], function(x){
					  
	                  # Addition of all the % of coverage at this interval. 
	                  y0=sum(x$diffFracBelowThreshold[x$covThreshold >=1 & x$covThreshold <5])
	                                    
	                  # If the addition is 0, we make sure they are marked as 0 and not NA
	                  if(length(y0)== 0){
	                      y0=0
	                  }
	                  y1=sum(x$diffFracBelowThreshold[x$covThreshold >=5 & x$covThreshold <10])
	                  if(length(y1)== 0){
					  	  y1=0
					  }
	                  y2=sum(x$diffFracBelowThreshold[x$covThreshold >=10 & x$covThreshold <20])
	                  if(length(y2)== 0){
					  	  y2=0
					  }
	                  y3=sum(x$diffFracBelowThreshold[x$covThreshold >=20])
	                  if(length(y3)== 0){
					  	  y3=0
					  }
					  # Total genome coverage.
	                  y4 <- sum(y0,y1,y2,y3)
	                  return(c(y0,y1,y2,y3,y4))
						}
					  )

	# Transform table into matrix
	summary_cov <- do.call(rbind,summary_cov)
	# Name columns
	colnames(summary_cov) <- c("x1-x4","x5-x9","x10-x19",">x20","total")
	#write.table(summary_cov, file=paste(sampleCoverageDir,sampleName,"_summaryCov.txt", sep= ''),sep="\t")
	# summary_cov:
	# gnm       	  x1          x5          x10         x20
	# AC_000001.1	0.8869967	0.7844005	0.7025351	0.60814771
	# AC_000002.1   0.280761	0.1780007	0.13370223	0.0825864199999999
	# AC_000004.1   0.269992	0.1507732	0.11396872	0.08871942

	# Data subset with genomes covered in at least 1x
	i <- (rowSums(summary_cov[,1:4]) !=0)
	dd <- summary_cov[i,]

	# Merge statistics and coverage tables.
	cov_def <- cbind(new_cov[new_cov$covMean > 0,],dd)
	#cov_def:
	#"gnm"	"covMean"	"covMin"	"covSD"	"covMedian"	"x1-x4"	"x5-x9"	"x10-x19"	">x20"	"total"
	#"AC_000007.1"	0.5	0	0.707106781186548	0.5	0.00178089	0	0	0	0.00178089
	#"genome"	22.8181818181818	0	14.0931662926476	22.5	9.36207e-06	3.400551e-06	1.5431484e-06	4.6904224e-07	1.477481164e-05
	#"NC_001493.2"	1.5	0	1.29099444873581	1.5	0.001750779	0	0	0	0.001750779
	#"NC_001875.2"	6.5	0	4.18330013267038	6.5	0.0003484981	0.0006212363	0.0005606278	0	0.0015303622
	#"NC_002794.1"	1	0	1.4142135623731	1	0.000301237	0	0	0	0.000301237
	write.table(cov_def, file=paste(sampleCoverageDir,sampleName,"_coverageTable.txt", sep= ''),sep="\t",row.names=F)

	# Plot the data. 
	# As long as the depth is below the max_cov, for each genome id it groups by gnm and applies the funcion
	by(cov, cov[,"gnm"], function(g) {
		# established at 500 for aesthetic reasons
		maxCov=500
	   	# check if genome coverage is not 0
	    if (mean(g$covThreshold)!=0){
	   		p1<-ggplot(subset(g, covThreshold<maxCov),aes(x=covThreshold, y=100*fracAboveThreshold)) +
			geom_line() + 
			ylim(0, 100) + 
			theme_bw() +
			theme(axis.text.x = element_text(size = 10.5,angle=75, vjust=0.5), strip.text.x = element_text(size=6.5)) + 
			labs(title=paste(g$gnm[1],"genome coverage", sep=' '), x="Depth of coverage", y="Percentage of coverage") 
			pdf(file=paste(sampleCoverageDir,g$gnm[1],"_coverage_graph.pdf",sep=''),width=15) 
			print(p1) 
			dev.off()
		}
		}
	)

}, warning = function(w) {
    
    
}, error = function(e) {
    # Empty file
    write.table('', file=paste(sampleCoverageDir,sampleName,"_coverageTable.txt", sep= ''),sep="\t",row.names=F)

}, finally = {
    
})



