#########################################################
#		  		SCRIPT TO MERGE RESULTS				 	#
#########################################################

# 1. Reads coverage and blast files. 
# 2. Generates txt file with the merged table.
# Note: This script should only be run after finishing the blast and coverage analysis of the sample for that organism. 

# Arguments:
# $1 (sampleName) = Name of the sample. (sampleName)
# $2 (organism) = Name of the organism directory (xx-organism)

# Input Files:
# sampleName_coverageTable.txt: File generated with graphs_coverage.R (In ANALYSIS/xx-organism/sampleName/coverage/)
# sampleName_BLASTn_filtered.blast: File generated by the blast script. (In ANALYSIS/xx-organism/sampleName/blast/)

# Output files: (In RESULTS/data/)
# sampleName_organism_results.txt: txt file of the merged results table.

# ARGUMENTS
args = commandArgs(trailingOnly=TRUE)
sampleName=args[1] # sampleName
organism=args[2] # xx-organism
analysisDir=args[3] # in config
resultsDir=args[4]  # in config
# CONSTANTS
sampleCoverageTable=paste(analysisDir, organism, "/", sampleName, "/coverage/", sampleName,"_coverageTable.txt", sep='')
sampleBlastTable=paste(analysisDir, organism, "/", sampleName, "/blast/",sampleName, "_BLASTn_filtered.blast", sep= '')
coverage=""

# READ BLAST FILE
#blast=read.table(sampleBlastTable, sep="\t", header=FALSE)
blast=read.delim(sampleBlastTable, sep="\t", header=FALSE)

# 	Name input files 
colnames(blast) <- c("Organism","Query_seq_id","Reference Id","% of identical matches","Alignment length", "Number of mismatches", 
					 "Number of Gap openings", "Start of alignment in query", "End of alignment in query", "Start of alignment in subject", 
					 "End of alignment in subject", "Expect value", "Bit Score", "Query")

# 	dropping query sequence
blast = subset(blast, select = c("Organism","Query_seq_id","Reference Id","% of identical matches","Alignment length", "Number of mismatches",
								 "Number of Gap openings", "Start of alignment in query", "End of alignment in query", "Start of alignment in subject",
								 "End of alignment in subject", "Expect value", "Bit Score"))

# Coverage may not be available
result = tryCatch({
	# READ COVERAGE FILE
    coverage=read.table(sampleCoverageTable, sep="\t", header=TRUE)

	coverage = subset(coverage, select = c("gnm", "covMean", "covMin", "covSD", "covMedian", "x1.x4", "x5.x9", "x10.x19", "X.x20", "total"))

}, warning = function(w) {
    
    
}, error = function(e) {
    # No coverage file, generate empty data frame
    coverage=data.frame(matrix(NA, nrow=nrow(blast), ncol=10))
    colnames(coverage) <- c("gnm", "covMean", "covMin", "covSD", "covMedian", "x1.x4", "x5.x9", "x10.x19", "X.x20", "total")

}, finally = {
    # 	merge files
	sampleResults = merge(x=blast, y=coverage, by.x = "Reference Id", by.y = "gnm")

	# WRITE OUTPUT FILE WITH MERGED TABLES
	organism=unlist(strsplit(organism, split='-', fixed=TRUE))[2]
	write.table(sampleResults, file=(paste(resultsDir, "/data/persamples/", sampleName, "_", organism, "_results.txt", sep="")), sep= '\t', col.names=FALSE, row.names=FALSE)
})



