#!/bin/bash
set -e

#########################################################
#		  			SAMPLES ID READER				 	#
#########################################################

# 1. Gets the sample name from the file names in 00-reads folder.
# Given raw read files with the following name structure:
# sampleName_R1*.fastq.gz and sampleName_R2*.fastqc.gz the sample name will be the string before _R1 reads file.
# Note: the file samples_id.txt is generated by samplesID_gen.sh

# Input Files (In analysisDir/00-reads/)
# sampleName1_*R1*.fastq.gz
# sampleName1_*R2*.fastq.gz
# sampleName2_*R1*.fastq.gz
# sampleName2_*R2*.fastq.gz
# sampleName3_*R1*.fastq.gz
# sampleName3_*R2*.fastq.gz
# ...

# Output Files (in analysisDir)
# samples_id.txt: File containing a list with the name of each sample.

#	CONSTANTS
source ./pikaVirus.config

readFolder="${analysisDir}/00-reads/"
>"${analysisDir}/samples_id.txt"

for file in ${readFolder}*.fastq*
do
	sampleName=$( basename $file )
	echo $sampleName | sed 's/\(.*\)\.fastq*/\1/' >> "${analysisDir}/samples_id.txt"
done

