#!/bin/bash
set -e

#########################################################
#		  		FUNGI MAPPER WRAPPER				 	#
#########################################################

# 1. Runs mapper_fungi.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_host_removal.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

source ./pikaVirus.config
source ${analysisDir}/SRC/mapper_fungi.sh
samplesIdFile="${analysisDir}/samples_id.txt"


if [ "${cluster}" == "yes" ] # qsub -V -j y -b y -cwd -t 1-16 -q all.q -N name command
then
	in=$(awk "NR==$SGE_TASK_ID" $samplesIdFile)
	map_fungi $in
else
	cat ${analysisDir}/samples_id.txt | while read in
	do
		map_fungi $in
	done
fi