#!/bin/bash
set -e

#########################################################
#		  		HOST REMOVAL WRAPPER				 	#
#########################################################

# 1. Runs host.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_preprocessing.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#	CONSTANTS
source ./pikaVirus.config
samplesIdFile="${analysisDir}/samples_id.txt"


if [ "${cluster}" == "yes" ] # qsub -V -j y -b y -cwd -t 1-number of samples -q all.q -N name command
then
	in=$(awk "NR==$SGE_TASK_ID" $samplesIdFile)
	bash ${analysisDir}/SRC/host.sh -s $in
else
	cat ${analysisDir}/samples_id.txt | while read in
	do
	    bash ${analysisDir}/SRC/host.sh -s $in
	done
fi
