#!/bin/bash
set -e

#########################################################
#		  			VIRUS BLAST WRAPPER				 	#
#########################################################

# 1. Runs blast.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_virus_assembly.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#       CONSTANTS
source ./pikaVirus.config
source ${analysisDir}/SRC/blast.sh
samplesIdFile="${analysisDir}/samples_id.txt"


if [ "${cluster}" == "yes" ] # qsub -V -j y -b y -cwd -t 1-number of samples -q all.q -N name command
then
	in=$(awk "NR==$SGE_TASK_ID" $samplesIdFile)
	sampleDir="${workingDir}ANALYSIS/06-virus/${in}/"
	blast $sampleDir $virDB
else
	cat ${analysisDir}/samples_id.txt | while read in
	do
		sampleDir="${workingDir}ANALYSIS/06-virus/${in}/"
		blast $sampleDir $virDB
	done
fi