#!/bin/bash
set -e

#########################################################
#		  		PREPROCESSING WRAPPER				 	#
#########################################################

# 1. Runs preprocessing.sh with every sample included in samples_id.txt*
# 2. Runs perl script to generate fastqc unified report
# * Note: the file samples_id.txt is generated by samplesID_gen.sh


#       CONSTANTS	
source ./pikaVirus.config
samplesIdFile="${analysisDir}/samples_id.txt"


if [ "${cluster}" == "yes" ] # qsub -V -j y -b y -cwd -t 1-number of samples -q all.q -N name command
then
	in=$(awk "NR==$SGE_TASK_ID" $samplesIdFile)
	bash ${analysisDir}/SRC/preprocessing.sh -s $in
else
	cat ${analysisDir}/samples_id.txt | while read in
	do 
		bash ${analysisDir}/SRC/preprocessing.sh -s $in
	done
fi
# generate fastqc report: 
# cp -r ${analysisDir}/SRC/html/quality/template.html ${workingDir}ANALYSIS/99-stats/

# perl ${analysisDir}/SRC/html/quality/listFastQCReports.pl ${workingDir}ANALYSIS/99-stats/data/ > ${workingDir}ANALYSIS/99-stats/table.html
# perl ${analysisDir}/SRC/html/quality/createHTML.pl

