#!/bin/bash
set -e

#########################################################
#		  		FUNGI COVERAGE WRAPPER				 	#
#########################################################

# 1. Runs coverage.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_fungi_mapper.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#       CONSTANTS
source ./pikaVirus.config
samplesIdFile="${analysisDir}/samples_id.txt"

# Calculates coverage for each sample
if [ "${cluster}" == "yes" ] # qsub -V -j y -b y -cwd -t 1-16 -q all.q -N name command
then
	in=$(awk "NR==$SGE_TASK_ID" $samplesIdFile)
	sampleDir="${analysisDir}/07-fungi/${in}/"
	bash ${analysisDir}/SRC/coverage.sh $sampleDir $fungiDB
else
	cat ${analysisDir}/samples_id.txt | while read in
	do
		sampleDir="${analysisDir}/07-fungi/${in}/"
		bash ${analysisDir}/SRC/coverage.sh $sampleDir $fungiDB
	done
fi
