#!/bin/bash
set -e

#########################################################
#		  	PARASITE ASSEMBLY WRAPPER				 	#
#########################################################

# 1. Runs assembly.sh* with every sample included in samples_id.txt**
# * Note: This script must only be used after running wrapper_parasite_mapper.sh
# ** Note: the file samples_id.txt is generated by samplesID_gen.sh

#       CONSTANTS
source ./pikaVirus.config
source ${analysisDir}/SRC/assembly.sh
samplesIdFile="${analysisDir}/samples_id.txt"


if [ "${cluster}" == "yes" ] # qsub -V -j y -b y -cwd -t 1-number of samples -q all.q -N name command
then
	in=$(awk "NR==$SGE_TASK_ID" $samplesIdFile)
	mappedProtozoaDir="${analysisDir}/08-protozoa/${in}/reads/"
	mappedInvertebrateDir="${analysisDir}/09-invertebrate/${in}/reads/"
	assemble $mappedProtozoaDir
	assemble $mappedInvertebrateDir
else
	cat ${analysisDir}/samples_id.txt | while read in
	do
		mappedProtozoaDir="${analysisDir}/08-protozoa/${in}/reads/"
		mappedInvertebrateDir="${analysisDir}/09-invertebrate/${in}/reads/"
		assemble $mappedProtozoaDir
		assemble $mappedInvertebrateDir
	done
fi